# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppseeEmbeddedRNIssues' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AppseeEmbeddedRNIssues
  pod 'Appsee'

  #target 'AppseeEmbeddedRNIssues-tvOSTests' do
  #  inherit! :search_paths
  #  # Pods for testing
  #end

  #target 'AppseeEmbeddedRNIssuesTests' do
  #  inherit! :search_paths
  #  # Pods for testing
  #end

end

#target 'AppseeEmbeddedRNIssues-tvOS' do
#  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#  # use_frameworks!
#
#  # Pods for AppseeEmbeddedRNIssues-tvOS
#
#  target 'AppseeEmbeddedRNIssues-tvOSTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end
#
#end
